package com.example.appdblibrary.entity.enums;

public enum Permissions {

    ADD_PERMISSIONS_ROLE,
    ADD_ROLE,
    ADD_CATEGORY,
    ADD_PRODUCT,
    ADD_FAVOURITE,
    ADD_SALE,
    ADD_BRANCH,
    ADD_RECOMMENDED_PRODUCT,

    DELETE_PERMISSIONS_ROLE,
    DELETE_ROLE,
    DELETE_CATEGORY,
    DELETE_PRODUCT,
    DELETE_SALE,
    DELETE_USER,
    DELETE_BRANCH,
    DELETE_RECOMMENDED_PRODUCT,

    EDIT_ROLE,
    EDIT_CATEGORY,
    EDIT_PRODUCT,
    EDIT_USER,
    EDIT_SALE,
    EDIT_BRANCH,
    EDIT_RECOMMENDED_PRODUCT,

    VIEW_CATEGORY,
    VIEW_PRODUCT,
    VIEW_ROLE,
    VIEW_USER,
    VIEW_SALE,
    VIEW_BRANCH,
    VIEW_RECOMMENDED_PRODUCT,

    DOWNLOAD_ATTACHMENT,
    UPLOAD_ATTACHMENT,
    MANAGE_ROLE_TO_USER,

    ;

}
